version: "3"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ./ollama-data:/root/.ollama # This may be better to be created as an docker volume instead of a bind mount


    # * Uncomment the following lines to enable GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: "nvidia" # or "mesa" for intel and amd gpus
    #           count: all # or a specific number of gpus
    #           capabilities: ["gpu"]
